### PR TITLE
Adding image to the readme to show what it looks like. 

### PR DESCRIPTION
**Pull request by logankilpatrick**
I will add more images in the future. I think this is a good start! #214

### CODE REVIEW

**Comment by NHDaly** [comment]
Thanks i do agree that this is helpful! 
Haha I worry a bit about encouraging people to call `loadurl` due to #150, but otherwise 👍 this is great, thanks!

**Comment by logankilpatrick** [comment]
Hm, `loadurl` worked fine for me

**Comment by NHDaly** [comment]
>Hm, loadurl worked fine for me

Yeah, the issue is that _after_ the `loadurl`, you can't issue future blink javascript commands

**Comment by NHDaly** [comment]
Anyway, i'll merge this now! Thanks for the contribution

**Comment by NHDaly** [comment]
@logankilpatrick oh, apparently there was a typo in the image link, which i've fixed here:
https://github.com/JuliaGizmos/Blink.jl/commit/05e18438a5157c3614eaaa482a9808a6c5966869

**Pull request merged**
