### PR TITLE
avoid using nested macros to work around #134

### PR DESCRIPTION
**Pull request by rdeits**
Sorry, this change isn't very pretty, but it's enough to work around #134 until we can address the root cause with https://github.com/JuliaGizmos/JSExpr.jl/pull/14 or something like it.

### CODE REVIEW

**Comment by pfitzseb** [comment]
I'm not opposed to merging this, but the issue does seem to be completly on the JSExpr.jl side, no?

**Comment by rdeits** [comment]
It's actually kind of complicated, and I'm not sure what the *right* fix would be. The problem is that Blink has code that looks like: 

```julia
@js w begin
  @new ....
end
```

That `@js` is a macro defined in Blink, which quotes its second argument and then passes that quoted expression to `JSExpr.jsexpr()`. The problem is that that quoted expression still contains the `@new` macro call. So what should JSExpr do with it? Currently, JSExpr tries to expand it in `current_module()`, which only actually works when the *user* has `@new` in their current scope (and might do completely the wrong thing if they have their own `@new` macro). Before my change in #125 , Blink had its own implementation of `jsexpr()` which expanded the macros in `Blink`, avoiding the problem. 

The proposed change in https://github.com/JuliaGizmos/JSExpr.jl/pull/14 would be essentially the same as what Blink had before #125. Rather than doing `macroexpand(Blink, ...)` it would do `macroexpand(JSExpr, ...)`, since that's where the macros definitions now live. I'm still wary about doing any manual macro expansion at all, but I think that change essentially gets us back to the working state we were in before I screwed it all up :wink:

**Comment by rdeits** [comment]
I think that's possible, but I haven't had time to test it. https://github.com/JuliaGizmos/JSExpr.jl/pull/14 turned out to be the wrong solution, so this is still something we need to resolve one way or another. I'm really sorry I can't be super helpful in solving this right now, as I'm in a bit of a last-minute thesis crunch. 

I think the current options are: 

1. In `Blink.@js`, do the macro expansion in Blink before handing the result to `JSExpr.jsexpr`. 
2. Manually expand the `@new` and `@var` macros where they appear in the Blink source (this PR)

**Comment by travigd** [comment]
Closing as stale.

**Pull request closed without merging**
