### PR TITLE
Add a docstring for `active(::Window)`

### PR DESCRIPTION
**Pull request by NHDaly**

### CODE REVIEW

**Comment by pfitzseb** [comment]
Unrelated to the dosctring, but shouldn't this be `isactive`?

**Comment by NHDaly** [comment]
I had the same thought. Or `isopen`?

My _guess_ is that the name came from the corresponding electron function?

Is it okay to just change it? I'm still a bit leery about making breaking
API changes in packages.

**Comment by pfitzseb** [comment]
Right, there probably is some merit to keeping Electron's function names.

**Comment by travigd** [comment]
FWIW I'm in the camp of making the exposed API as Julian as possible. I don't think there's a huge mental mismatch between `active` and `isactive` and the latter is way more common in Julia.

Also, I think changing it with a deprecation warning is 100% fine (i.e. `Base.@deprecate ...`).

**Comment by travigd** [comment]
On the other hand, a lot of the API surface isn't very Julian (in terms of naming conventions) right now so maybe we should just leave it as in and update it in a major release.

Aaaaaalso, we should release v1.0.0 soon, there's no point (imo) in having a viable package that's pre-1.0 and bumping to 1.0 allows us to use real semver.

**Comment by NHDaly** [comment]
I'm fine with either approach! I'm going to just merge this now, and I like the idea of doing a juliafication pass over the API as a major version number release! :)

**Comment by NHDaly** [comment]
> On the other hand, a lot of the API surface isn't very Julian (in terms of naming conventions) right now so maybe we should just leave it as in and update it in a major release (`active` to `isactive`, `title` to `title!`, etc.)

@travigd I just came across an open issue for doing just that. Adding cross-reference: https://github.com/JuliaGizmos/Blink.jl/issues/161

**Pull request merged**
