### PR TITLE
Add compat bounds for all dependencies.

### PR DESCRIPTION
**Pull request by travigd**

### CODE REVIEW

**Comment by tkoolen** [comment]
MacroTools unfortunately also dropped 0.7 support when it dropped 0.6 support for some reason. MacroTools 0.4 should install and work on Julia 0.7, I think.

**Comment by travigd** [comment]
I was leaning towards dropping 0.7 support (thoughts?).

**Comment by tkoolen** [comment]
That's another option. But it kind of becomes this cascade where now dependencies of this package also need to stop testing on / advertising support for 0.7, and not really for a good technical reason. I think MacroTools 0.4 will be fine for testing on 0.7 for the foreseeable future. And if not, we could always switch then, or submit a trivial PR to MacroTools to change the `compat` to get their latest.

I believe you do need an upper bound on `julia` in the `compat` section to get the version tag auto-merge bot to work by the way.

**Comment by travigd** [comment]
I see your point but I also don't think 0.7 is in wide use today. Plus it causes some issues with Travis (which are fixable but...).

**Comment by tkoolen** [comment]
Do whatever you think is best. It's not a huge deal either way.

**Pull request merged**
