### PR TITLE
loadurl blocks until page is loaded

### LINKED ISSUE #41: Make loadurl synchronous
I think programming with Blink is better if everything is synchronous by default.

With #35, I made opening a Window synchronous. Next, I want to make loading a URL synchronous/blocking.

Any thoughts?

### PR DESCRIPTION
**Pull request by EricForgy**
Closes #41

### CODE REVIEW

**Comment by EricForgy** [comment]
This needs revision.

**Comment by EricForgy** [comment]
Hi @Varanas, @one-more-minute  and @spencerlyon2 ,

I'm not sure how you feel about this change, but I like it and hope you do too (?)

This PR is based on #45 because I figure if you don't like that one, you won't like this one either :sweat_smile: 

These two PRs make it friendlier, in my experience, to program with and to test Blink.

For example, now we can do something like this in code:

~~~julia
    w = Window()
    loadurl("http://www.julialang.org")
    println("Got it!")
    close(w)
~~~

With asynchronous Window() and loadurl, there is no way I can think of to run the above code without manually waiting for each step to complete.

This will also make writing tests cleaner. Instead of

~~~julia
w = Window(); sleep(5.0)
@test 1 == 1
~~~

we can do things like

~~~julia
@test length(Blink.windows()) == 0
w = Window()
@test length(Blink.windows()) == 1
close(w)
@test length(Blink.windows()) == 0
~~~

**Comment by Varanas** [comment]
I do think making these operations blocking is a good idea! That said, I haven't actually worked with Blink yet, so that opinion is purely theoretical ;)

**Comment by EricForgy** [comment]
Haha :D Thanks for the theoretical support :)

There may be a better way to accomplish the same thing, so I am interested in suggestions too.

**Comment by spencerlyon2** [comment]
Hey @EricForgy you say that this and #45 implement the same thing. Do you think it is a good idea to close one of these, or should we review both?

**Comment by EricForgy** [comment]
Hi @spencerlyon2 ,

#45 just has the blocking for opening a Window and this PR adds to #45 by also blocking loadurl. I suppose I can close #45 in favor of this one because this one includes #45 and if there are any issues with #45, they are probably also issues with this PR. 

Sorry for the confusion. I'll go ahead and close #45. Thanks!

**Comment by spencerlyon2** [comment]
I will defer to @one-more-minute on this one. 

He's done some real work to maintain a lot of js async semantics and I'm not sure if he wants to move away from that.

**Comment by travigd** [comment]
Closing as stale.

**Pull request closed without merging**
